[workspace]
authors = ["Anthony Aufdenkampe <aaufdenkampe@limno.com>"]
channels = ["conda-forge"]
name = "soil_modeling"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.5,<3.15"
pandas = ">=3.0.3,<4"
numpy = ">=2.4.6,<3"
jupyterlab = ">=4.5.8,<5"
ipykernel = ">=7.2.0,<8"
matplotlib = ">=3.10.9,<4"

[pypi-dependencies]
rosetta-soil = ">=0.3.2, <0.4"
